name: test

on:
  pull_request:
    branches:
      - main

concurrency:
  group:  ${{ github.workflow }}-${{github.event_name}}-${{ github.ref }}
  cancel-in-progress: true      

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: update action.yml to build locally
        run: |
          sed -i 's/.*image\:.*/  image\: \"Dockerfile\"/' action.yml
          cat action.yml      

      - name: build
        uses: ./ # Uses an action in the root directory
        with:
          action: build

      - name: export
        uses: ./ # Uses an action in the root directory
        with:
          export: png
          output: images

      - name: build with binary
        uses: ./ # Uses an action in the root directory
        with:
          output: dist-binary
          use-dot-bin: 'true'

      - name: codegen react
        uses: ./ # Uses an action in the root directory
        with:
          action: codegen

      - name: codegen mmd
        uses: ./ # Uses an action in the root directory
        with:
          codegen: mmd
          output: mmd
